project_id = "kazcwhshptkxolxnmpel"

[functions.manage-profiles]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.voice-clone]
verify_jwt = false